### PR TITLE
Navbar image

### PR DESCRIPTION
**Pull request by sgopalani12**
made commit and added navbar-image background on the following screens:
-settings
-image screens

I also got rid of previous background image from image screen page

### CODE REVIEW

**Review by gent1999 — DISMISSED** [review]
Looks good to me!

**Review by gent1999 — COMMENTED** [review]
ArtForYou shouldnt have this ImageBackground import

**Review by gent1999 — APPROVED** [review]
Now it looks good

**Review by Rchrdlss3 — APPROVED** [review]
lgtm

**Pull request merged**
